# Name of the workflow
name: "Build"

# Controls when the workflow will run
# This workflow runs only on pushes to the main branch
on:
  push:
    branches: [main]
    # paths:
    #   - "**.java"

# Defines the workflow's environment variables
# Can be accessed via $VARIABLE_NAME 
env:
  PLUGIN_JAR: "example-1.0.0-SNAPSHOT.jar"
  PLUGIN_DIR: "/var/lib/neo4j/plugins"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains a two jobs that run sequentially
jobs:
  # Build and test the code
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        shell: bash
        run: mvn clean package

      - name: Upload plugin JAR ${{ env.PLUGIN_JAR }}
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jar
          path: target/${{ env.PLUGIN_JAR }}

  # Deploy the plugin to the remote Neo4j server
  deploy:
    runs-on: ubuntu-latest
    needs: [build] # this job depends on the build job

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download plugin JAR ${{ env.PLUGIN_JAR }} from the build job
        uses: actions/download-artifact@v3
        id: download
        with:
          name: plugin-jar

      # https://github.com/appleboy/scp-action
      - name: Upload plugin JAR to remote Neo4j server using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: ${{ env.PLUGIN_JAR }}
          target: "." # target directory on remote server

      # https://github.com/appleboy/ssh-action
      - name: Move plugin and update permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script_stop: true
          script: |
            sudo mv ${{ env.PLUGIN_JAR }} ${{ env.PLUGIN_DIR }}

            sudo chown neo4j:neo4j ${{ env.PLUGIN_DIR }}/${{ env.PLUGIN_JAR }}

            sudo chmod +x ${{ env.PLUGIN_DIR }}/${{ env.PLUGIN_JAR }}

      # https://github.com/appleboy/ssh-action
      - name: Restart Neo4j serice
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script_stop: true
          script: |
            sudo systemctl restart neo4j
            sudo systemctl status -l neo4j.service

