# Name of the workflow
name: "Build"

# Controls when the workflow will run
# This workflow runs only on pushes to the main branch
on:
  push:
    branches: [main]
    # paths:
    #   - "**.java"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains a two jobs that run sequentially
jobs:
  # Build and test the code
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - id: build
        name: Build with Maven
        shell: bash
        run: mvn clean package

      - name: Upload plugin JAR
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jar
          path: target/procedure-template-1.0.0-SNAPSHOT.jar

  # Deploy the plugin to the remote Neo4j server
  deploy:
    runs-on: ubuntu-latest
    needs: [build] # this job depends on the build job

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download plugin JAR from the build workflow
        uses: actions/download-artifact@v3
        id: download
        with:
          name: plugin-jar

      # https://github.com/appleboy/scp-action
      - name: Upload plugin JAR to remote Neo4j server using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: procedure-template-1.0.0-SNAPSHOT.jar
          target: "." # target directory on remote server

      # https://github.com/appleboy/ssh-action
      - name: Move plugin and update permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script_stop: true
          script: |
            sudo mv procedure-template-1.0.0-SNAPSHOT.jar /var/lib/neo4j/plugins
            sudo chown -R neo4j:neo4j /var/lib/neo4j/plugins/procedure-template-1.0.0-SNAPSHOT.jar
            sudo chmod +x /var/lib/neo4j/plugins/procedure-template-1.0.0-SNAPSHOT.jar

      # https://github.com/appleboy/ssh-action
      - name: Restart Neo4j serice
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script_stop: true
          script: |
            sudo systemctl restart neo4j
            sudo systemctl status -l neo4j.service

