name: "CI"

on:
  push:
    branches: [main]

env:
  PLUGIN_JAR: "example-1.0.0.jar"
  PLUGIN_DIR: "/var/lib/neo4j/plugins"

jobs:
  # Build and test the code
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Build and test with Maven
        shell: bash
        run: mvn clean package

      - name: Cache plugin JAR ${{ env.PLUGIN_JAR }}
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jar
          path: target/${{ env.PLUGIN_JAR }}

  # Deploy the plugin to the remote Neo4j server
  deploy:
    runs-on: ubuntu-latest
    needs: [build] # this job depends on the build job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore plugin JAR ${{ env.PLUGIN_JAR }}
        uses: actions/download-artifact@v3
        id: download
        with:
          name: plugin-jar

      - name: Upload plugin JAR to remote Neo4j server using SCP
        uses: appleboy/scp-action@master # https://github.com/appleboy/scp-action
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: ${{ env.PLUGIN_JAR }}
          target: "." # target directory on remote server

      - name: Move plugin and update permissions
        uses: appleboy/ssh-action@master # https://github.com/appleboy/ssh-action
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script_stop: true
          script: |
            sudo mv ${{ env.PLUGIN_JAR }} ${{ env.PLUGIN_DIR }}

            sudo chown neo4j:neo4j ${{ env.PLUGIN_DIR }}/${{ env.PLUGIN_JAR }}

            sudo chmod +x ${{ env.PLUGIN_DIR }}/${{ env.PLUGIN_JAR }}

      - name: Restart Neo4j service 
        uses: appleboy/ssh-action@master # https://github.com/appleboy/ssh-action
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script_stop: true
          script: |
            sudo systemctl restart neo4j
            sudo systemctl status -l neo4j.service

